TEDX/Tedx/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tedx/', include('write.urls', namespace='write')),
]

TEDX/write/urls.py
from . import views
from django.urls import path

app_name = 'write'

urlpatterns = [
    
    path('', views.home, name='home'),
]

TEDX/write/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from taggit.managers import TaggableManager 
#from ckeditor.fields import RichTextField 

# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)
    


class Topic(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
 
    
       
class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True, null=True)
    bio = models.TextField(null=True)

    Photo = models.ImageField(null=True, default="avatar.svg")

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    
    
class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'
    
    tags = TaggableManager()
    
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True, related_name='Tposts')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='Uposts')
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    body = models.TextField()
    image = models.ImageField(upload_to='posts/%Y/%m/%d/', blank=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
    objects = models.Manager()
    published = PublishedManager()
    
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    
    class Meta:
        ordering = ['-publish']
        indexes = [
            models.Index(fields=['-publish']),
        ]
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('write:post_detail', 
                       args=[ self.publish.year, self.publish.month, self.publish.day, self.slug])
        
    #path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),   
        
    
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='commentss')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='commentedd')
    body = models.TextField()
    image = models.ImageField(upload_to='comments/%Y/%m/%d/', blank=True)
    
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]
        
    def __str__(self):
        return f'Comment by {self.author} on {self.post} '
    

TEDX/write/forms.py
from django import forms 
from .models import User, Comment, Post


class UserForm(forms.Form):
    class Meta:
        model = User
        fields = ['name', 'email', 'password1', 'password2']
    
    
class PostForm(forms.Form):
    class Meta:
        model = Post
        fields = ['topic', 'author', 'title', 'body', 'image' ]
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['author', 'body']
        
class SearchForm(forms.Form):
    query = forms.CharField()

TEDX/write/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout

from .models import Topic, User, Post, Comment
from .forms import  UserForm, PostForm, CommentForm, SearchForm

# Create your views here.




def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    posts = Post.objects.filter(
        Q(topic__name__icontains=q) |
        Q(title__icontains=q) |
        Q(body__icontains=q)
    )

    topics = Topic.objects.all()[0:5]
   
    context = { 'topics': topics, 'posts': posts}
    
    return render(request, 'write/home.html', context)

TEDX/write/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
    <title>Freedom of Speech- Here you can express your opinion freely </title>
</head>

<body>
    
    {%  include 'navbar.html' %}


    {% block content %}

    {% endblock %}

    <script src="{% static 'js/script-old.js' %}"></script>
</body>

</html>

TEDX/write/templates/navbar.html
{% load static %}

<header class="header header--loggedIn">
  <div class="container">

    <a href="{% url 'write:home' %}" class="header__logo">
      <img src="{% static 'images/freedom.png' %}" />
      <h1>Tweet</h1>
    </a>

    <form class="header__search" method="GET" action="{% url 'write:home' %}">
      <label>
        <svg
          version="1.1"
          xmlns="http://www.w3.org/2000/svg"
          width="32"
          height="32"
          viewBox="0 0 32 32"
        >
          <title>search</title>
          <path
            d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
          ></path>
        </svg>
        <input name="q" placeholder="Search for posts" />
      </label>
    </form>
    
    <div class="user">
      {% if request.user.is_authenticated %}
      Hello {{ request.user.first_name|default:request.user.username }},
      <a href="#">Logout</a>
      {% else %}
      <a href="#">Log-in</a>
      {% endif %}
    </div>

  </div>
</header>

TEDX/write/templates/write/home.html
{% extends 'main.html' %}

{% block content %}

<main class="layout">
    <div class="side-topics">
        <h1>Explore Topics</h1>
        <ul>
            <li>Programming</li>
            <li>Data Science</li>
            <li>Technology</li>
            <li>Self Improvement</li>
            <li>Writing</li>
            <li>Relationships</li>
            <li>Machine Learning</li>
            <li>Productivity</li>
            <li>Politics</li>
        </ul>
        <p>See more topics</p>
    </div>

    <div class="container">
        <h1>The Purest of Doggos</h1>
        <div class="grid-container">
            <div>
                <img class='grid-item grid-item-1' src='https://images.unsplash.com/photo-1544568100-847a948585b9?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ' alt=''>
                <p>"I'm so happy today!"</p>
            </div>
            <div>
                <img class='grid-item grid-item-2' src='https://images.unsplash.com/photo-1517423440428-a5a00ad493e8?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ' alt=''>
                <p>"I see those nugs."</p>
            </div>
            <div>
                <img class='grid-item grid-item-3' src='https://images.unsplash.com/photo-1510771463146-e89e6e86560e?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ' alt=''>
                <p>"I love you so much!"</p>
            </div>
            <div>
                <img class='grid-item grid-item-4' src='https://images.unsplash.com/photo-1507146426996-ef05306b995a?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ' alt=''>
                <p>"I'm the baby of the house!"</p>
            </div>
            <div>
                <img class='grid-item grid-item-5' src='https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ' alt=''>
                <p>"Are you gunna throw the ball?"</p>
            </div>
            <div>
                <img class='grid-item grid-item-6' src='https://images.unsplash.com/photo-1548199973-03cce0bbc87b?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ' alt=''>
                <p>"C'mon friend!"</p>
            </div>
            <div>
                <img class='grid-item grid-item-7' src='https://images.unsplash.com/photo-1552053831-71594a27632d?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ' alt=''>
                <p>"A rose for mommy!"</p>
            </div>
            <div>
                <img class='grid-item grid-item-8' src='https://images.unsplash.com/photo-1518717758536-85ae29035b6d?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ' alt=''>
                <p>"You gunna finish that?"</p>
            </div>
            <div>
                <img class='grid-item grid-item-9' src='https://images.unsplash.com/photo-1535930891776-0c2dfb7fda1a?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ' alt=''>
                <p>"We can't afford a cat!"</p>
            </div>
            <div>
                <img class='grid-item grid-item-10' src='https://images.unsplash.com/photo-1504595403659-9088ce801e29?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=400&fit=max&ixid=eyJhcHBfaWQiOjE0NTg5fQ' alt=''>
                <p>"Dis my fren!"</p>
            </div>
  
        </div>
    </div>

</main>

{% endblock %}